"""Add AccessLog model and PaymentLog.created_at field

Revision ID: 1001c8195ac2
Revises: 20c4aeb9783d
Create Date: 2025-04-11 04:47:41.046881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1001c8195ac2'
down_revision = '20c4aeb9783d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jockeys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('jockeys_id_seq'::regclass)"))

    with op.batch_alter_table('payment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('payment_date')
        batch_op.drop_column('plan_type')
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plan_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('jockeys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('jockeys_id_seq'::regclass)"))

    op.drop_table('access_logs')
    # ### end Alembic commands ###
