"""
マイグレーションファイルを修正します。
jockeys テーブルの id カラムの型変更を削除し、
必要なテーブルと列のみを追加します。
"""

# 既存のマイグレーションファイルを編集
# 以下のように修正

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('path', sa.String(length=200), nullable=True),
        sa.Column('method', sa.String(length=10), nullable=True),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('user_agent', sa.String(length=200), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # PaymentLog テーブルに created_at 列を追加
    op.add_column('payment_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # jockeys テーブルの id 列の型変更を削除
    # 以下の行をコメントアウトまたは削除
    # with op.batch_alter_table('jockeys', schema=None) as batch_op:
    #     batch_op.alter_column('id', existing_type=sa.BIGINT(), type_=sa.Integer())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # jockeys テーブルの id 列の型変更を削除
    # 以下の行をコメントアウトまたは削除
    # with op.batch_alter_table('jockeys', schema=None) as batch_op:
    #     batch_op.alter_column('id', existing_type=sa.Integer(), type_=sa.BIGINT())
    
    # PaymentLog テーブルから created_at 列を削除
    op.drop_column('payment_logs', 'created_at')
    
    # access_logs テーブルを削除
    op.drop_table('access_logs')
    # ### end Alembic commands ### 