"""add race reviews table

Revision ID: 32b75082742b
Revises: f54596027ad5
Create Date: 2024-11-05 03:52:56.280377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b75082742b'
down_revision = 'f54596027ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('pace_analysis', sa.Text(), nullable=True),
    sa.Column('track_condition_note', sa.Text(), nullable=True),
    sa.Column('race_flow', sa.Text(), nullable=True),
    sa.Column('overall_impression', sa.Text(), nullable=True),
    sa.Column('winner_analysis', sa.Text(), nullable=True),
    sa.Column('placed_horses_analysis', sa.Text(), nullable=True),
    sa.Column('notable_performances', sa.Text(), nullable=True),
    sa.Column('future_prospects', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('races_backup_20241103')
    op.drop_table('horse_notes')
    op.drop_table('entries_backup_20241103')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('jockey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('track_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('weather',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('track_condition',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.alter_column('venue',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('track_condition',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('weather',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('track_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('jockey_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('entries_backup_20241103',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('race_id', sa.INTEGER(), nullable=True),
    sa.Column('horse_id', sa.INTEGER(), nullable=True),
    sa.Column('jockey_id', sa.INTEGER(), nullable=True),
    sa.Column('horse_number', sa.INTEGER(), nullable=True),
    sa.Column('odds', sa.REAL(), nullable=True),
    sa.Column('popularity', sa.INTEGER(), nullable=True),
    sa.Column('horse_weight', sa.INTEGER(), nullable=True),
    sa.Column('weight_change', sa.INTEGER(), nullable=True),
    sa.Column('prize', sa.REAL(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('frame_number', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.REAL(), nullable=True),
    sa.Column('time', sa.TEXT(), nullable=True),
    sa.Column('margin', sa.TEXT(), nullable=True),
    sa.Column('passing', sa.TEXT(), nullable=True),
    sa.Column('last_3f', sa.REAL(), nullable=True)
    )
    op.create_table('horse_notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('horse_id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races_backup_20241103',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('date', sa.NUMERIC(), nullable=True),
    sa.Column('start_time', sa.TEXT(), nullable=True),
    sa.Column('track_type', sa.TEXT(), nullable=True),
    sa.Column('distance', sa.INTEGER(), nullable=True),
    sa.Column('direction', sa.TEXT(), nullable=True),
    sa.Column('weather', sa.TEXT(), nullable=True),
    sa.Column('track_condition', sa.TEXT(), nullable=True),
    sa.Column('venue', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True)
    )
    op.drop_table('race_reviews')
    # ### end Alembic commands ###
