"""add admin field

Revision ID: 588bb5f774a1
Revises: 1b953122deca
Create Date: 2024-11-06 06:59:07.381126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588bb5f774a1'
down_revision = '1b953122deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_reviews', schema=None) as batch_op:
        batch_op.alter_column('sale_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'free'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('race_reviews', schema=None) as batch_op:
        batch_op.alter_column('sale_status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'free'"))

    # ### end Alembic commands ###
