"""create initial tables

Revision ID: 8deb1e128765
Revises: 
Create Date: 2025-02-26 10:35:41.077908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8deb1e128765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('trainer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jockeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=50), nullable=True),
    sa.Column('venue_id', sa.String(length=50), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('race_year', sa.Integer(), nullable=True),
    sa.Column('kai', sa.String(length=20), nullable=True),
    sa.Column('nichi', sa.String(length=20), nullable=True),
    sa.Column('race_class', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('track_type', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('weather', sa.String(length=20), nullable=True),
    sa.Column('track_condition', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index('idx_race_date_desc', [sa.text('date DESC')], unique=False)
        batch_op.create_index('idx_race_date_venue', ['date', 'venue'], unique=False)
        batch_op.create_index('idx_race_number', ['race_number'], unique=False)
        batch_op.create_index('idx_race_venue_id', ['venue_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True),
    sa.Column('point_balance', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('blog', sa.String(length=100), nullable=True),
    sa.Column('youtube', sa.String(length=100), nullable=True),
    sa.Column('specialties', sa.String(length=200), nullable=True),
    sa.Column('analysis_style', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=True),
    sa.Column('horse_id', sa.BigInteger(), nullable=True),
    sa.Column('jockey_id', sa.BigInteger(), nullable=True),
    sa.Column('horse_number', sa.Integer(), nullable=True),
    sa.Column('odds', sa.String(length=10), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('horse_weight', sa.Integer(), nullable=True),
    sa.Column('weight_change', sa.Integer(), nullable=True),
    sa.Column('prize', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('margin', sa.String(length=10), nullable=True),
    sa.Column('passing', sa.String(length=20), nullable=True),
    sa.Column('last_3f', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index('idx_entry_position', ['position'], unique=False)
        batch_op.create_index('idx_entry_race_horse', ['race_id', 'horse_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horse_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('pace_analysis', sa.Text(), nullable=True),
    sa.Column('track_condition_note', sa.Text(), nullable=True),
    sa.Column('race_flow', sa.Text(), nullable=True),
    sa.Column('overall_impression', sa.Text(), nullable=True),
    sa.Column('winner_analysis', sa.Text(), nullable=True),
    sa.Column('placed_horses_analysis', sa.Text(), nullable=True),
    sa.Column('notable_performances', sa.Text(), nullable=True),
    sa.Column('future_prospects', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_status', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shutuba_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('horse_id', sa.BigInteger(), nullable=False),
    sa.Column('jockey_id', sa.BigInteger(), nullable=True),
    sa.Column('bracket_number', sa.Integer(), nullable=True),
    sa.Column('horse_number', sa.Integer(), nullable=True),
    sa.Column('weight_carry', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shutuba_entries', schema=None) as batch_op:
        batch_op.create_index('idx_shutuba_jockey', ['jockey_id'], unique=False)
        batch_op.create_index('idx_shutuba_race_horse', ['race_id', 'horse_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_race', sa.Boolean(), nullable=True),
    sa.Column('notification_memo', sa.Boolean(), nullable=True),
    sa.Column('items_per_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('review_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['race_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_responses')
    op.drop_table('review_purchases')
    op.drop_table('user_settings')
    op.drop_table('user_point_logs')
    op.drop_table('support_tickets')
    with op.batch_alter_table('shutuba_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_shutuba_race_horse')
        batch_op.drop_index('idx_shutuba_jockey')

    op.drop_table('shutuba_entries')
    op.drop_table('race_reviews')
    op.drop_table('race_memos')
    op.drop_table('race_details')
    op.drop_table('payment_logs')
    op.drop_table('notifications')
    op.drop_table('membership_change_logs')
    op.drop_table('login_history')
    op.drop_table('horse_memos')
    op.drop_table('favorites')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('idx_entry_race_horse')
        batch_op.drop_index('idx_entry_position')

    op.drop_table('entries')
    op.drop_table('users')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index('idx_race_venue_id')
        batch_op.drop_index('idx_race_number')
        batch_op.drop_index('idx_race_date_venue')
        batch_op.drop_index('idx_race_date_desc')

    op.drop_table('races')
    op.drop_table('jockeys')
    op.drop_table('horses')
    # ### end Alembic commands ###
