"""add created_at to users

Revision ID: 96241dce02eb
Revises: e83762476a04
Create Date: 2024-11-05 14:57:35.146786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96241dce02eb'
down_revision = 'e83762476a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('trial_start')
        batch_op.drop_column('trial_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('trial_start', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
