"""Add status column to review_purchases

Revision ID: 97f07848063b
Revises: e5fd24c58b79
Create Date: 2024-11-07 03:50:02.353480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f07848063b'
down_revision = 'e5fd24c58b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_purchases', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
