"""Add profile fields to User model

Revision ID: a957190551ed
Revises: 97f07848063b
Create Date: 2024-11-07 05:54:39.168364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a957190551ed'
down_revision = '97f07848063b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_purchases', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blog', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialties', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('analysis_style', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('analysis_style')
        batch_op.drop_column('specialties')
        batch_op.drop_column('youtube')
        batch_op.drop_column('blog')
        batch_op.drop_column('note')
        batch_op.drop_column('twitter')
        batch_op.drop_column('introduction')
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('review_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
